"""MCP-level error codes shared by collect and analyze handlers."""

from __future__ import annotations

from enum import Enum


class MCPErrorCode(str, Enum):
    COLLECT_VALIDATION_FAILED = "COLLECT_VALIDATION_FAILED"
    COLLECT_TIMEOUT = "COLLECT_TIMEOUT"
    COLLECT_RUNTIME_ERROR = "COLLECT_RUNTIME_ERROR"

    ANALYSIS_INVALID_INPUT = "ANALYSIS_INVALID_INPUT"
    ANALYSIS_TIMEOUT = "ANALYSIS_TIMEOUT"
    ANALYSIS_RUNTIME_ERROR = "ANALYSIS_RUNTIME_ERROR"

    REPORT_GENERATION_FAILED = "REPORT_GENERATION_FAILED"
